"""Abstract port interfaces for the LLM Client library.

Defines the LLMClientPort abstract base class that all LLM provider
adapters must implement, providing a unified interface for chat completion,
streaming, and embedding generation.
"""

from abc import ABC, abstractmethod
from typing import AsyncIterator

from sona_llm.models import CompletionResult, LLMProviderConfig, Message


class LLMClientPort(ABC):
    """Abstract port for LLM provider interactions.

    All LLM provider adapters (Ollama, OpenAI, Anthropic, Google AI)
    must implement this interface to participate in the Sona AI OS LLM
    ecosystem. This enables transparent provider switching, failover,
    and multi-provider routing through a single abstraction.
    """

    @abstractmethod
    async def chat_completion(
        self,
        messages: list[Message],
        model_config: LLMProviderConfig,
    ) -> CompletionResult:
        """Execute a non-streaming chat completion request.

        Args:
            messages: The conversation history as a list of messages.
            model_config: Provider and model configuration for this request.

        Returns:
            A CompletionResult containing the generated content, model info,
            token usage, and latency metrics.
        """
        ...

    @abstractmethod
    async def stream_completion(
        self,
        messages: list[Message],
        model_config: LLMProviderConfig,
    ) -> AsyncIterator[str]:
        """Execute a streaming chat completion request.

        Yields tokens/chunks as they are generated by the LLM provider,
        enabling low-latency streaming responses to end users.

        Args:
            messages: The conversation history as a list of messages.
            model_config: Provider and model configuration for this request.

        Yields:
            String chunks/tokens as they are streamed from the provider.
        """
        ...

    @abstractmethod
    async def generate_embedding(
        self,
        text: str,
    ) -> list[float]:
        """Generate a vector embedding for the given text.

        Args:
            text: The input text to embed.

        Returns:
            A list of floats representing the embedding vector.
        """
        ...

    @abstractmethod
    async def generate_embeddings_batch(
        self,
        texts: list[str],
    ) -> list[list[float]]:
        """Generate vector embeddings for multiple texts in a single batch.

        More efficient than calling generate_embedding() multiple times
        when embeddings are needed for many texts simultaneously.

        Args:
            texts: List of input texts to embed.

        Returns:
            A list of embedding vectors, one per input text, in the same order.
        """
        ...
