"""Abstract port interfaces for the AI Kernel service.

Defines the contracts that infrastructure adapters must implement
to provide AI reasoning, model routing, and kernel processing capabilities.
"""

from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from typing import Any

from sona_ai_kernel.domain.models import (
    KernelRequest,
    KernelResponse,
    ModelConfig,
    ReasoningStrategy,
)


class AIKernelPort(ABC):
    """Primary port for the AI Kernel service.

    Defines the contract for processing requests through the AI Kernel pipeline.
    All concrete implementations (e.g., LangChain, raw LLM adapters) must
    satisfy this interface.
    """

    @abstractmethod
    async def process(self, request: KernelRequest) -> KernelResponse:
        """Process a single request through the kernel pipeline.

        Args:
            request: The kernel request containing content, context, and config.

        Returns:
            A KernelResponse with generated content and usage metrics.
        """
        ...

    @abstractmethod
    async def stream(self, request: KernelRequest) -> AsyncIterator[str]:
        """Stream response tokens for a request.

        Args:
            request: The kernel request containing content, context, and config.

        Yields:
            String tokens/chunks as they are generated by the model.
        """
        ...

    @abstractmethod
    async def select_model(self, request: KernelRequest) -> ModelConfig:
        """Select the optimal model based on request characteristics.

        Analyzes the request (content, context, strategy) to determine
        the best model configuration for the task.

        Args:
            request: The kernel request to analyze.

        Returns:
            A ModelConfig specifying the selected provider and model.
        """
        ...


class ReasoningEnginePort(ABC):
    """Port for pluggable reasoning strategies.

    Infrastructure adapters implement this port to provide various
    reasoning approaches such as chain-of-thought or tree-of-thought.
    """

    @abstractmethod
    async def reason(
        self,
        prompt: str,
        context: dict[str, Any],
        strategy: ReasoningStrategy,
    ) -> list[str]:
        """Execute a reasoning chain and return the reasoning trace.

        Args:
            prompt: The input prompt to reason about.
            context: Additional contextual information for reasoning.
            strategy: The reasoning strategy to apply.

        Returns:
            A list of reasoning steps representing the trace.
        """
        ...


class ModelRouterPort(ABC):
    """Port for model selection and routing across providers.

    Infrastructure adapters implement this port to determine the optimal
    model for a given request, considering availability, cost, and capability.
    """

    @abstractmethod
    async def route(self, request: KernelRequest) -> ModelConfig:
        """Determine the best model for the given request.

        Args:
            request: The kernel request to route.

        Returns:
            A ModelConfig for the selected model.
        """
        ...

    @abstractmethod
    async def list_available(self) -> list[ModelConfig]:
        """List all available models across all configured providers.

        Returns:
            A list of ModelConfig instances for all available models.
        """
        ...
