"""Code Generator — AI-powered code generation and transformation."""

from __future__ import annotations

import ast
from dataclasses import dataclass, field


@dataclass
class GenerationResult:
    """Result of a code generation or transformation operation."""

    content: str
    language: str = "python"
    success: bool = True
    message: str = ""


@dataclass
class TestGenerationResult(GenerationResult):
    """Result of test generation."""

    test_framework: str = "pytest"
    test_count: int = 0
    test_types: list[str] = field(default_factory=list)


class CodeGenerator:
    """Generates, refactors, and transforms code.

    Supports:
        - Code generation from descriptions
        - Test generation from source code
        - Documentation generation
        - Code refactoring
        - Template-based code scaffolding
    """

    TEMPLATES = {
        "python-module": {
            "description": "Python module with class and functions",
            "files": ["__init__.py", "main.py", "schemas.py"],
        },
        "fastapi-endpoint": {
            "description": "FastAPI CRUD endpoint with schemas",
            "files": ["router.py", "schemas.py", "service.py"],
        },
        "pydantic-model": {
            "description": "Pydantic data model with validation",
            "files": ["schemas.py"],
        },
        "python-script": {
            "description": "Standalone Python script with CLI",
            "files": ["main.py"],
        },
    }

    def __init__(self) -> None:
        self._indent = "    "

    def generate_from_source(
        self, source: str, task: str, language: str = "python"
    ) -> GenerationResult:
        """Generate transformed code based on a task."""
        if task == "refactor":
            return self.refactor_code(source, language)
        if task == "add_tests":
            test_result = self.generate_tests(source, language)
            return GenerationResult(content=test_result.content, language=test_result.language)
        if task == "add_docs":
            return self.generate_documentation(source, language)
        return GenerationResult(content=source, success=True, message="No transformation applied")

    def generate_tests(self, source: str, language: str = "python") -> TestGenerationResult:
        """Generate test code from source code."""
        if language != "python":
            return TestGenerationResult(
                content=f"# Test generation for {language} is not yet supported",
                language=language,
                success=False,
                message=f"Test generation for {language} requires manual implementation",
            )

        tests = []
        test_types = set()
        test_count = 0

        try:
            tree = ast.parse(source)
        except SyntaxError:
            return TestGenerationResult(
                content="# Source file has syntax errors -- cannot generate tests",
                success=False,
                message="Source has syntax errors",
            )

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                name = node.name
                if name.startswith("_"):
                    continue
                params = [arg.arg for arg in node.args.args]
                test_count += 1
                test_types.add("function")
                if params:
                    test_code = self._make_param_test(name, params)
                else:
                    test_code = self._make_simple_test(name)
                tests.append(test_code)

            elif isinstance(node, ast.ClassDef):
                methods = [
                    n.name
                    for n in ast.walk(node)
                    if isinstance(n, ast.FunctionDef) and not n.name.startswith("_")
                ]
                if methods:
                    test_count += len(methods)
                    test_types.add("class")
                    for m in methods:
                        tests.append(self._make_method_test(node.name, m))

        if not tests:
            tests.append('def test_placeholder():\n    """Placeholder test."""\n    assert True\n')

        lines = ['"""Tests auto-generated by Sona AI Coding Assistant."""', ""]
        lines.append("import pytest")
        lines.append("")
        for test in tests:
            lines.append(test)
            lines.append("")

        return TestGenerationResult(
            content="\n".join(lines),
            test_count=test_count,
            test_types=list(test_types),
        )

    def generate_documentation(self, source: str, language: str = "python") -> GenerationResult:
        """Generate documentation from source code."""
        docs = []
        try:
            tree = ast.parse(source)
        except SyntaxError:
            docs.append("> **Source file has syntax errors -- documentation may be incomplete**\n")

        has_classes = False
        has_functions = False
        total_lines = len(source.split("\n"))

        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                has_classes = True
                docstring = ast.get_docstring(node) or ""
                methods = [
                    n.name
                    for n in ast.walk(node)
                    if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and not n.name.startswith("_")
                ]
                docs.append(f"### Class: `{node.name}`")
                if docstring:
                    docs.append(f"\n{docstring}\n")
                if methods:
                    docs.append("\n**Methods:** `{}`\n".format(", ".join(methods)))

            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                has_functions = True
                docstring = ast.get_docstring(node) or ""
                if not docstring:
                    params = [arg.arg for arg in node.args.args]
                    if params:
                        docstring = "Function `{}` with parameters: {}.".format(
                            node.name, ", ".join(params)
                        )
                    else:
                        docstring = f"Function `{node.name}`."
                docs.append(f"### Function: `{node.name}`")
                docs.append(f"\n{docstring}\n")

        header = "# Module Documentation\n\n"
        header += "**File:** `module.py`\n"
        header += f"**Source lines:** {total_lines}\n"
        header += f"**Language:** {language}\n\n"
        header += "## Overview\n\n"

        if has_classes:
            classes_found = [n for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]
            header += f"- {len(classes_found)} classes\n"
        if has_functions:
            funcs_found = [
                n for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
            ]
            # Only count top-level functions
            header += f"- {len(funcs_found)} functions\n"

        header += "\n## API Reference\n\n"
        body = "\n".join(docs) if docs else "*No public API found*"

        return GenerationResult(
            content=header + body,
            language="markdown",
        )

    def refactor_code(self, source: str, language: str = "python") -> GenerationResult:
        """Apply automated refactoring to source code."""
        try:
            ast.parse(source)
        except SyntaxError:
            return GenerationResult(
                content=source,
                success=False,
                message="Cannot refactor: source has syntax errors",
            )

        # Simple refactoring stub
        refactorings_applied = []
        new_source = source
        if new_source != source:
            refactorings_applied.append("Modernized string formatting")
            source = new_source

        return GenerationResult(
            content=source,
            message="; ".join(refactorings_applied)
            if refactorings_applied
            else "No refactoring needed",
        )

    @staticmethod
    def _make_simple_test(func_name: str) -> str:
        """Generate a simple test for a function with no parameters."""
        lines = []
        lines.append(f"def test_{func_name}():")
        lines.append(f'    """Test the {func_name} function."""')
        lines.append(f"    # TODO: Implement test for {func_name}")
        lines.append(f"    result = {func_name}()")
        lines.append(
            f'    assert result is not None, f"Expected non-None result from {func_name}()"'
        )
        return "\n".join(lines) + "\n"

    @staticmethod
    def _make_param_test(func_name: str, params: list[str]) -> str:
        """Generate a test for a function with parameters."""
        param_str = ", ".join(params)
        lines = []
        lines.append(f"def test_{func_name}():")
        lines.append(f'    """Test the {func_name} function."""')
        lines.append("    # Arrange")
        for i, p in enumerate(params):
            lines.append(f"    param_{i} = None  # TODO: Set test value for {p}")
        params_list = ", ".join(f"param_{i}" for i in range(len(params)))
        lines.append(f"    params = [{params_list}]")
        lines.append("")
        lines.append("    # Act")
        lines.append(f"    result = {func_name}({param_str})")
        lines.append("")
        lines.append("    # Assert")
        lines.append(f'    assert result is not None, "{func_name}() should return a result"')
        return "\n".join(lines) + "\n"

    @staticmethod
    def _make_method_test(class_name: str, method_name: str) -> str:
        """Generate a test for a class method."""
        lines = []
        test_name = f"test_{class_name.lower()}_{method_name}"
        lines.append(f"def {test_name}():")
        lines.append(f'    """Test {class_name}.{method_name}."""')
        lines.append("    # Arrange")
        lines.append(f"    instance = {class_name}()")
        lines.append("")
        lines.append("    # Act")
        lines.append(f"    result = instance.{method_name}()")
        lines.append("")
        lines.append("    # Assert")
        lines.append(f'    assert result is not None, "{class_name}.{method_name}() should return"')
        return "\n".join(lines) + "\n"
